name: Machine Learning CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  mlflow-ci-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install mlflow scikit-learn pandas numpy

      - name: Build MLflow Docker Image
        run: |
          cd Workflow-CI/MLProject
          mlflow models build-docker -m "runs:/dummy_run_id/model" -n "iqbaltawakal/ml-model-ci:latest"